version: "3.9"

services:
  calendarsvc:
    container_name: calendar_svc
    build:
      context: .
      dockerfile: ./build/calendar/Dockerfile
    ports:
      - "8080:8081"
    restart: on-failure
    environment:
      HTTP_PORT: "8081"
      GRPC_PORT: "8082"
      DB_GRPC_PORT: "8084"
      DB_CONTAINER_NAME: "dbsvc"
    depends_on:
      - dbsvc
    networks:
      - db_bridge

  dbsvc:
    container_name: db_svc
    build:
      context: .
      dockerfile: ./build/db/Dockerfile
    ports:
      - "5000:8081"
      - "8084:8084"
    restart: on-failure
    environment:
      HTTP_PORT: "8081"
      GRPC_PORT: "8084"
      DATABASE_URL: "postgres://gouser:gopassword@db:5432/gotest?sslmode=disable"
    depends_on:
      - db
      - migrate
    networks:
      - db_bridge

  db:
    image: postgres:alpine
    restart:
      always
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d/
      - database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: gotest
      POSTGRES_USER: gouser
      POSTGRES_PASSWORD: gopassword
    networks:
      - db_bridge

  migrate:
    image: migrate/migrate
    networks:
      - db_bridge
    depends_on:
      - db
    volumes:
      - ./db/migrations:/migrations
    command:
      [ "-path", "/migrations", "-database",  "postgres://gouser:gopassword@db:5432/gotest?sslmode=disable", "up" ]

networks:
  db_bridge:
    driver: bridge

volumes:
  database-data: